blueprint:
  name: 4-Button Scene Switch by MOES
  description: Automate your 4-Button Scene Switch by MOES using ZHA events.
  domain: automation
  source_url: https://github.com/PeterHewat/HA_Blueprints/blob/main/zha-MOES-4-button-scene-switch-TS0044_by_TZ3000_wkai4ga5.yaml
  input:
    ts0044_device:
      name: TS0044 Remote
      selector:
        device:
          integration: zha
          manufacturer: _TZ3000_wkai4ga5
          model: TS0044
          filter:
            model: TS0044

    # Actions
    button_1_short_press:
    button_1_double_press:
    button_1_long_press:
    button_2_short_press:
    button_2_double_press:
    button_2_long_press:
    button_3_short_press:
    button_3_double_press:
    button_3_long_press:
    button_4_short_press:
    button_4_double_press:
    button_4_long_press:

mode: parallel
max: 10

trigger:
  # Button 1
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_1
    id: b1-1
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: button_1
    id: b1-2
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: button_1
    id: b1-l

    # Button 2
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_2
    id: b2-1
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: button_2
    id: b2-2
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: button_2
    id: b2-l

    # Button 3
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_3
    id: b3-1
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: button_3
    id: b3-2
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: button_3
    id: b3-l

    # Button 4
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_4
    id: b4-1
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: button_4
    id: b4-2
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: button_4
    id: b4-l

action:
  - choose:
      # Button 1
      - conditions:
          - condition: trigger
            id:
              - b1-1
        sequence: !input button_1_short_press
      - conditions:
          - condition: trigger
            id:
              - b1-2
        sequence: !input button_1_double_press
      - conditions:
          - condition: trigger
            id:
              - b1-l
        sequence: !input button_1_long_press

      # Button 2
      - conditions:
          - condition: trigger
            id:
              - b2-1
        sequence: !input button_2_short_press
      - conditions:
          - condition: trigger
            id:
              - b2-2
        sequence: !input button_2_double_press
      - conditions:
          - condition: trigger
            id:
              - b2-l
        sequence: !input button_2_long_press

      # Button 3
      - conditions:
          - condition: trigger
            id:
              - b3-1
        sequence: !input button_3_short_press
      - conditions:
          - condition: trigger
            id:
              - b3-2
        sequence: !input button_3_double_press
      - conditions:
          - condition: trigger
            id:
              - b3-l
        sequence: !input button_3_long_press

      # Button 4
      - conditions:
          - condition: trigger
            id:
              - b4-1
        sequence: !input button_4_short_press
      - conditions:
          - condition: trigger
            id:
              - b4-2
        sequence: !input button_4_double_press
      - conditions:
          - condition: trigger
            id:
              - b4-l
        sequence: !input button_4_long_press
