blueprint:
  name: 4-Button Scene Switch by MOES
  description: Automate your 4-Button Scene Switch by MOES using ZHA events.
  domain: automation
  source_url: https://github.com/PeterHewat/HA_Blueprints/blob/main/zha-MOES-4-button-scene-switch-TS0044_by_TZ3000_wkai4ga5.yaml
  input:
    ts0044_device:
      name: TS0044 Remote
      selector:
        device:
          filter:
            model: TS0044

    # Actions
    button_1_short_press:
      name: Actions for Button 1 Short Press
      default:
      selector:
        action:

    button_1_double_press:
      name: Actions for Button 1 Double Press
      default:
      selector:
        action:

    button_1_long_press:
      name: Actions for Button 1 Long Press
      default:
      selector:
        action:

    button_2_short_press:
      name: Actions for Button 2 Short Press
      default:
      selector:
        action:

    button_2_double_press:
      name: Actions for Button 2 Double Press
      default:
      selector:
        action:

    button_2_long_press:
      name: Actions for Button 2 Long Press
      default:
      selector:
        action:

    button_3_short_press:
      name: Actions for Button 3 Short Press
      default:
      selector:
        action:

    button_3_double_press:
      name: Actions for Button 3 Double Press
      default:
      selector:
        action:

    button_3_long_press:
      name: Actions for Button 3 Long Press
      default:
      selector:
        action:

    button_4_short_press:
      name: Actions for Button 4 Short Press
      default:
      selector:
        action:

    button_4_double_press:
      name: Actions for Button 4 Double Press
      default:
      selector:
        action:

    button_4_long_press:
      name: Actions for Button 4 Long Press
      default:
      selector:
        action:

mode: parallel
max: 10

trigger:
  # Button 1
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_1
    id: b1-S
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: button_1
    id: b1-D
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: button_1
    id: b1-L

    # Button 2
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_2
    id: b2-S
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: button_2
    id: b2-D
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: button_2
    id: b2-L

    # Button 3
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_3
    id: b3-S
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: button_3
    id: b3-D
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: button_3
    id: b3-L

    # Button 4
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_4
    id: b4-S
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: button_4
    id: b4-D
  - device_id: !input ts0044_device
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: button_4
    id: b4-L

action:
  - choose:
      # Button 1
      - conditions:
          - condition: trigger
            id:
              - b1-S
        sequence: !input button_1_short_press
      - conditions:
          - condition: trigger
            id:
              - b1-D
        sequence: !input button_1_double_press
      - conditions:
          - condition: trigger
            id:
              - b1-L
        sequence: !input button_1_long_press

      # Button 2
      - conditions:
          - condition: trigger
            id:
              - b2-S
        sequence: !input button_2_short_press
      - conditions:
          - condition: trigger
            id:
              - b2-D
        sequence: !input button_2_double_press
      - conditions:
          - condition: trigger
            id:
              - b2-L
        sequence: !input button_2_long_press

      # Button 3
      - conditions:
          - condition: trigger
            id:
              - b3-S
        sequence: !input button_3_short_press
      - conditions:
          - condition: trigger
            id:
              - b3-D
        sequence: !input button_3_double_press
      - conditions:
          - condition: trigger
            id:
              - b3-L
        sequence: !input button_3_long_press

      # Button 4
      - conditions:
          - condition: trigger
            id:
              - b4-S
        sequence: !input button_4_short_press
      - conditions:
          - condition: trigger
            id:
              - b4-D
        sequence: !input button_4_double_press
      - conditions:
          - condition: trigger
            id:
              - b4-L
        sequence: !input button_4_long_press
